version: '3.8'  # You can adjust the version as needed

services:
  nginx:
    hostname: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    hostname: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9000:9000
    environment:
      WP_NAME: ${WP_NAME}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_HOST: ${WP_HOST}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_EMAIL: ${WP_EMAIL}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
  
  mariadb:
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIA_NAME: ${MARIA_NAME}
      MARIA_USER: ${MARIA_USER}
      MARIA_PASSWORD: ${MARIA_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      device: /home/mdarify/data/mariadb
      o: bind
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: /home/mdarify/data/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
